apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fdd57swih-go 
  janus-idp.io/tekton: fdd57swih-go
  backstage.io/kubernetes-id: fdd57swih-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fdd57swih-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  